// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:id": {
    params: {
      "id": string;
    };
  };
  "/U/:id": {
    params: {
      "id": string;
    };
  };
  "/exam": {
    params: {};
  };
  "/face-detection": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:id" | "/U/:id" | "/exam" | "/face-detection" | "/sign-up";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/_student-dash.$id/route.tsx": {
    id: "routes/_student-dash.$id/route";
    page: "/:id";
  };
  "routes/_teacher-dash.$id/route.tsx": {
    id: "routes/_teacher-dash.$id/route";
    page: "/U/:id";
  };
  "routes/exam/route.tsx": {
    id: "routes/exam/route";
    page: "/exam";
  };
  "routes/face-detection/route.tsx": {
    id: "routes/face-detection/route";
    page: "/face-detection";
  };
  "routes/_auth.sign-up/route.tsx": {
    id: "routes/_auth.sign-up/route";
    page: "/sign-up";
  };
};