// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/student-dash/:id": {
    params: {
      "id": string;
    };
  };
  "/teacher-dash/:id": {
    params: {
      "id": string;
    };
  };
  "/exam": {
    params: {};
  };
  "/face-detection": {
    params: {};
  };
  "/get-started": {
    params: {};
  };
  "/teacher-dash/:id/new-test": {
    params: {
      "id": string;
    };
  };
  "/test/:test_id": {
    params: {
      "test_id": string;
    };
  };
  "/start-test/:testId": {
    params: {
      "testId": string;
    };
  };
  "/start-test/:testId/details": {
    params: {
      "testId": string;
    };
  };
  "/test/:testId/start": {
    params: {
      "testId": string;
    };
  };
  "/api/record-violations": {
    params: {};
  };
  "/api/submit-test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/student-dash/:id" | "/teacher-dash/:id" | "/exam" | "/face-detection" | "/get-started" | "/teacher-dash/:id/new-test" | "/test/:test_id" | "/start-test/:testId" | "/start-test/:testId/details" | "/test/:testId/start" | "/api/record-violations" | "/api/submit-test";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/student-dash.$id/route.tsx": {
    id: "routes/student-dash.$id/route";
    page: "/student-dash/:id";
  };
  "routes/teacher-dash.$id/route.tsx": {
    id: "routes/teacher-dash.$id/route";
    page: "/teacher-dash/:id";
  };
  "routes/exam/route.tsx": {
    id: "routes/exam/route";
    page: "/exam";
  };
  "routes/face-detection/route.tsx": {
    id: "routes/face-detection/route";
    page: "/face-detection";
  };
  "routes/auth/route.tsx": {
    id: "routes/auth/route";
    page: "/get-started";
  };
  "routes/teacher-dash.$id/new-test.tsx": {
    id: "routes/teacher-dash.$id/new-test";
    page: "/teacher-dash/:id/new-test";
  };
  "routes/teacher-dash.$id/test.$test_id.tsx": {
    id: "routes/teacher-dash.$id/test.$test_id";
    page: "/test/:test_id";
  };
  "routes/start-test/start-test.$testID.tsx": {
    id: "routes/start-test/start-test.$testID";
    page: "/start-test/:testId";
  };
  "routes/start-test/start-test.$testID.details.tsx": {
    id: "routes/start-test/start-test.$testID.details";
    page: "/start-test/:testId/details";
  };
  "routes/start-test/start-test.$testID.start.tsx": {
    id: "routes/start-test/start-test.$testID.start";
    page: "/test/:testId/start";
  };
  "routes/api/record-violations.tsx": {
    id: "routes/api/record-violations";
    page: "/api/record-violations";
  };
  "routes/api/submit-test.tsx": {
    id: "routes/api/submit-test";
    page: "/api/submit-test";
  };
};