// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/student-dash/:id": {
    params: {
      "id": string;
    };
  };
  "/teacher-dash/:id": {
    params: {
      "id": string;
    };
  };
  "/exam": {
    params: {};
  };
  "/face-detection": {
    params: {};
  };
  "/get-started": {
    params: {};
  };
  "/teacher-dash/:id/new-test": {
    params: {
      "id": string;
    };
  };
  "/test/:test_id": {
    params: {
      "test_id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/student-dash/:id" | "/teacher-dash/:id" | "/exam" | "/face-detection" | "/get-started" | "/teacher-dash/:id/new-test" | "/test/:test_id";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/student-dash.$id/route.tsx": {
    id: "routes/student-dash.$id/route";
    page: "/student-dash/:id";
  };
  "routes/teacher-dash.$id/route.tsx": {
    id: "routes/teacher-dash.$id/route";
    page: "/teacher-dash/:id";
  };
  "routes/exam/route.tsx": {
    id: "routes/exam/route";
    page: "/exam";
  };
  "routes/face-detection/route.tsx": {
    id: "routes/face-detection/route";
    page: "/face-detection";
  };
  "routes/auth/route.tsx": {
    id: "routes/auth/route";
    page: "/get-started";
  };
  "routes/teacher-dash.$id/new-test.tsx": {
    id: "routes/teacher-dash.$id/new-test";
    page: "/teacher-dash/:id/new-test";
  };
  "routes/teacher-dash.$id/test.$test_id.tsx": {
    id: "routes/teacher-dash.$id/test.$test_id";
    page: "/test/:test_id";
  };
};